In [ ]:
### Numpy is a fundamental library in python, for scientific computing.

In [ ]:
import numpy as np

# creating 1D array
arr1=np.array([1,2,3,4,5]) # you provide a list, it will be converted to array
print(arr1)
arr2=np.array((1,2,3,4,5)) # you provide a tuple, it will also be converted to array
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [7]:
print(arr1.shape)
# 1D array so it will print (5,)-> meaning it has only 5 elements, and there are no rows and columns

(5,)


In [9]:
arr1.reshape(1,5)
# changing the 1D array into 2D. (1,5)-> meaning change the array into a 2D array having 1row and 5 columns

array([[1, 2, 3, 4, 5]])

In [11]:
# defining a 2D array
arr2=np.array([[1,2,3,4]]) # concept of nested list

arr2.shape # (1,4)-> meaning 1 row and 4 columns

(1, 4)

In [16]:
# 2D array with multiple rows and columns
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]]) # created a 3x3 matrix
print(arr2)

print(arr2.shape) #(3,3)-> meaning 3 row and 3 columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [21]:
# creating an array within a specified range
myArr=np.arange(0,10,2)
# creates an array with elements between 0(inclusive) and 10(exclusive), with a step of 2
print(myArr)

# convert this array into a 2D array, with 5 rows and 1 column
print(myArr.reshape(5,1))



[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [22]:
# create a 2D array with all elements as 1
oneArr=np.ones((3,4)) # 2D array with 3 rows and 4 columns and all elements as 1
print(oneArr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
# similarly, matrix with zeroes
zeroArr=np.zeros((3,4))
print(zeroArr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# create a nxn identity matrix
identity=np.eye(4) # 4x4 identity matrix
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
### Numpy Vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

In [27]:
# element wise addition
print(f"Addition: {arr1+arr2}") 

Addition: [11 22 33 44 55]


In [28]:
# element wise subtracion
print(f"Subtraction: {arr2-arr1}") 

Subtraction: [ 9 18 27 36 45]


In [29]:
# element wise multiplication
print(f"Multiplication: {arr1*arr2}") 

Multiplication: [ 10  40  90 160 250]


In [30]:
# element wise division
print(f"Division: {arr1/arr2}") 

Division: [0.1 0.1 0.1 0.1 0.1]


In [31]:
### Universal Functions-> functions which get applied to all array elements
arr1=np.array([1,2,3,4,5])

In [32]:
# square root-> element wise
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [34]:
# exponential-> to the power(e)
print(np.exp(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [36]:
# sine -> element wise
print(np.sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [37]:
# natural log-> element wise
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
# accessing a matrix element
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# arr[row][column]
print(arr[0][2]) # element from row->0 and column->2

3


In [45]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
# suppose we want to fetch [7 8] [11 12] from the matrix
# 7,8 are in row->1 
# 11,12 are in row->2(last row)
# so let's fetch those two rows
print(matrix[1:]) # this means start from row->1 and go till last

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
# now [7,8] are in column->2,3 (3 being the last column)
# same goes for [11,12]
# so we'll start from column 2 and go till last
print(matrix[1:,2:]) # 2: -> means start from column 2 and go till last

[[ 7  8]
 [11 12]]


In [ ]:
# similarly if you want to take [3,4] and [7,8] from the array
print(matrix[:2]) # start from 0th row and go till row 2(exclusive)

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
print(matrix[:2,2:]) # start from column-> 2 and go till last column

[[3 4]
 [7 8]]


In [52]:
# to pickup [6,7] and [10,11]
print(matrix[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
print(matrix[1:,1:3])

[[ 6  7]
 [10 11]]


In [55]:
# modify array elements
matrix[0][0]=100
print(matrix)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
### Statistical concepts 
# normalization

In [56]:
# calculating mean and standard deviation and then normalized data
data=np.array([10,20,30,40,50])

In [57]:
# calculating mean of the data
mean=np.mean(data)
print(mean)

30.0


In [ ]:
# calculating variance of data
variance=np.var(data)
print(variance)

200.0


In [ ]:
# and standard deviation = root(variance)
print(np.sqrt(variance))

14.142135623730951


In [60]:
# calculating standard deviation directly
sd=np.std(data)
print(sd)

14.142135623730951


In [61]:
# calculation of normalized data
print(data-mean)

[-20. -10.   0.  10.  20.]


In [63]:
normalized_data=(data-mean)/sd
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [65]:
### Logical operations
data=np.array([1,2,3,4,5,6,7,8])

print(data>5) # this operation is applied to every element of the array, and a new boolean array is returned based on the result

[False False False False False  True  True  True]


In [ ]:
# fetching datas based on a condition
print(data[data>5])
# only the elements from array which satisfy the condition, are fetched

[6 7 8]


In [68]:
print(data[(data>=2)&(data<=7)])

[2 3 4 5 6 7]
